# Generated by Django 3.1.4 on 2021-03-14 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210314_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquiz',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
