# Generated by Django 3.1.4 on 2021-03-14 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210314_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
